services:
  otel-collector:
    image: otel/opentelemetry-collector:0.108.0
    container_name: otel-collector
    command: [--config=/etc/otel-collector-config.yaml]
    volumes: 
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"
    depends_on:
      - data-prepper
  
  data-prepper:
    # dataprepper>=2.5.0 needs a newer cpu
    # dataprepper==2.5.0 can export to 2.9.0>=opensearch>=2.5.0
    image: opensearchproject/data-prepper:2.5.0
    container_name: data-prepper
    volumes:
      - ./dataprepper/pipelines.yaml:/usr/share/data-prepper/pipelines/pipelines.yaml
      - ./dataprepper/data-prepper-config.yaml:/usr/share/data-prepper/config/data-prepper-config.yaml
    ports:
      - "21890:21890" # port traces
      - "21891:21891" # port metrics