receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
      grpc:
        endpoint: 0.0.0.0:4317

exporters:
  otlp/traces:
    endpoint: data-prepper:21890
    tls:
      insecure: true
      insecure_skip_verify: true
  otlp/metrics:
    endpoint: data-prepper:21891
    tls:
      insecure: true
      insecure_skip_verify: true
  logging:

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/traces]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/metrics]
